name: get-maven

on:
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
  JAVA_VERSION: 17

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  get-maven:
    runs-on: ubuntu-latest
    steps:

    - name: get-maven
      shell: bash
      run: |
        wget -O apache-maven-3.9.11-bin.zip https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.11/apache-maven-3.9.11-bin.zip
